# 配置服务器信息
server:
  port: 21010

spring:
  datasource:
    url: jdbc:mysql://192.168.0.82:3306/sys?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

eureka:
  instance:
    hostname: 127.0.0.1  #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false   #false 表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务
    service-url:
      # 单机版配置defaultZone：设置与eureka server 交互的地址查询服务和注册服务都需要依赖的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 集群配置
#      defaultZone: http://eureka21020.com:21020/eureka/,http://eureka21030.com:21030/eureka/